import sqlite3 as sq
import hashlib
import secrets

# Description:
#       uses BLAKE2 to generate a hash
# Pre:
#       password (string)
# Post:
#       Hash and Salt
def get_secure_hash(password):

    # Generate a salt using a secure number generator
    salt = secrets.token_hex(16)

    # We use the blake2 hashing algorithm as it is collision resistant.
    # (SHA256 and others are probably fine but have been shown to have a, at least not insignificant, collision rate)
    hasher = hashlib.blake2s()

    # Get the hash for the salted password. Note that we append the salt on the end.
    hasher.update((password + salt).encode())
    hash = hasher.hexdigest()

    return {'hash': hash, 'salt': salt}


# Description:
#       Takes in a password and a salt and returns a hash
#       using the BLAKE2 Algorithm
# Pre:
#       password (string)
#       salt (string) -- Appended to the end of the password
# Post:
#       Hash generated from the salted password.
def get_password_hash(password, salt):
    
    # Create a hasher and pass in salted password
    hasher = hashlib.blake2s()
    hasher.update((password + salt).encode())

    return hasher.hexdigest()


# Description:
#       Returns a success if user exists and pass is correct.
def authenticate_user(user_name, password, connection):

    cursor = connection.cursor()

    query = '''
        SELECT password_hash, password_salt
        FROM users
        WHERE user_name == ?
    '''
    cursor.execute(query, (user_name,))
    hash_details = cursor.fetchall()[0]

    if len(hash_details) == 0:
        return (False, "user_not_found")
    
    password_hash = get_password_hash(password, hash_details[1])

    if password_hash == hash_details[0]:
        return (True, "auth_success")
    else:
        return (False, "incorrect_pass")


# Description: 
#       Creates a New User in the database
# Pre:
#       user_name (string) -- must be unique
#       password (string)
#       first_name (string)
#       last_name (string)
# Post:
#       Inserts into the database the new user.
def create_new_user(user_name, password, first_name, last_name, connection):

    cursor = connection.cursor()

    # Query for checking if the user is in the database
    # This could be optimized a bit
    query = '''
        SELECT user_name
        FROM users
        WHERE user_name == ?
    '''

    # Execute the query
    cursor.execute(query, (user_name,))

    # Fetch the query results
    results = cursor.fetchall()

    # If there is a user that already has this name
    # return an error
    if len(results) != 0:
        return (False, "account_exists")
    else:

        # SQL to call
        query = '''
            INSERT INTO
                users(
                    user_name,
                    password_salt,
                    password_hash,
                    first_name,
                    last_name
                )
            VALUES (?,?,?,?,?)
        '''

        # Get salt and hash generated by the password
        hashing = get_secure_hash(password)

        # Insert the user and commit
        cursor.execute(
            query, 
            (user_name, hashing['salt'], hashing['hash'], first_name, last_name)
        )

        connection.commit()

        # Commit to the database
        return (True, "account_created")

# Description: 
#       Update the password for an existing user.
# Pre:
#       user_name (string) -- must be unique
#       password (string)
#       first_name (string)
#       last_name (string)
# Post:
#       Inserts into the database the new user.
def update_user_password(user_name, new_pass, connection):

    cursor = connection.cursor()
    
    # Get a salt and the corresponding hash for the new password
    sh = get_secure_hash(new_pass)

    query = '''
        UPDATE users
        SET password_salt = ?, password_hash = ?
        WHERE user_name = ?
    '''

    # Update and commit
    cursor.execute(query, (sh['salt'], sh['hash'], user_name))
    connection.commit()